export const EXERCISES = [
  {id:'sq',   name:'Przysiad ze sztangą',     cat:'Legs',diff:'intermediate',equipment:['barbell'],               muscles:'Kwadryceps, pośladki, dwugłowe', muscleIds: ['quadriceps', 'gluteal', 'hamstring']},
  {id:'bp',   name:'Wyciskanie na ławce',      cat:'Push',diff:'intermediate',equipment:['barbell','bench'],       muscles:'Klatka piersiowa, triceps', muscleIds: ['chest', 'triceps']},
  {id:'dl',   name:'Martwy ciąg',              cat:'Pull',diff:'advanced',    equipment:['barbell'],               muscles:'Plecy, pośladki, dwugłowe', muscleIds: ['lower-back', 'upper-back', 'gluteal', 'hamstring']},
  {id:'ohp',  name:'Overhead Press',           cat:'Push',diff:'intermediate',equipment:['barbell'],               muscles:'Barki, triceps', muscleIds: ['front-deltoids', 'back-deltoids', 'triceps']},
  {id:'row',  name:'Wiosłowanie sztangą',      cat:'Pull',diff:'intermediate',equipment:['barbell'],               muscles:'Plecy, biceps', muscleIds: ['upper-back', 'lower-back', 'biceps']},
  {id:'pu',   name:'Pompki',                   cat:'Push',diff:'beginner',    equipment:['bodyweight'],            muscles:'Klatka, triceps, barki', muscleIds: ['chest', 'triceps', 'front-deltoids']},
  {id:'pu_d', name:'Pompki z uniesieniem nóg', cat:'Push',diff:'intermediate',equipment:['bodyweight'],            muscles:'Górna klatka, barki', muscleIds: ['chest', 'front-deltoids']},
  {id:'chin', name:'Podciąganie Chin-up',      cat:'Pull',diff:'intermediate',equipment:['pullup_bar'],            muscles:'Biceps, plecy, core', muscleIds: ['biceps', 'upper-back', 'abs']},
  {id:'pull', name:'Podciąganie Pull-up',      cat:'Pull',diff:'advanced',    equipment:['pullup_bar'],            muscles:'Plecy, tylne barki', muscleIds: ['upper-back', 'back-deltoids']},
  {id:'lunge',name:'Wykroki z hantlami',       cat:'Legs',diff:'beginner',    equipment:['dumbbells'],             muscles:'Kwadryceps, pośladki', muscleIds: ['quadriceps', 'gluteal']},
  {id:'dbs',  name:'Wyciskanie hantli',        cat:'Push',diff:'beginner',    equipment:['dumbbells','bench'],     muscles:'Klatka, triceps', muscleIds: ['chest', 'triceps']},
  {id:'dbr',  name:'Wiosłowanie hantlą',       cat:'Pull',diff:'beginner',    equipment:['dumbbells'],             muscles:'Plecy, biceps', muscleIds: ['upper-back', 'biceps']},
  {id:'rdl',  name:'Rumuński martwy ciąg',     cat:'Legs',diff:'intermediate',equipment:['dumbbells'],             muscles:'Dwugłowe uda, pośladki', muscleIds: ['hamstring', 'gluteal']},
  {id:'gobsq',name:'Goblet Squat',             cat:'Legs',diff:'beginner',    equipment:['dumbbells'],             muscles:'Kwadryceps, core', muscleIds: ['quadriceps', 'abs']},
  {id:'pike', name:'Pompki Pike',              cat:'Push',diff:'beginner',    equipment:['bodyweight'],            muscles:'Barki, triceps', muscleIds: ['front-deltoids', 'triceps']},
  {id:'inv',  name:'Wiosłowanie odwrócone',    cat:'Pull',diff:'beginner',    equipment:['bodyweight'],            muscles:'Plecy, biceps', muscleIds: ['upper-back', 'biceps']},
  {id:'bulg', name:'Bułgarski Przysiad',       cat:'Legs',diff:'intermediate',equipment:['bodyweight','dumbbells'],muscles:'Kwadryceps, pośladki', muscleIds: ['quadriceps', 'gluteal']},
  {id:'dips', name:'Dipy na poręczach', cat:'Push', diff:'intermediate', equipment:['dip_bar'], muscles:'Triceps, klatka', muscleIds: ['triceps', 'chest']},
  {id:'core', name:'Deska (Plank)',            cat:'Core',diff:'beginner',    equipment:['bodyweight'],            muscles:'Core, brzuch', muscleIds: ['abs', 'obliques']},
  {id:'abrv', name:'Ab Rollout',               cat:'Core',diff:'advanced',    equipment:['ab_roller'],             muscles:'Brzuch, core', muscleIds: ['abs', 'obliques', 'lower-back']},
  {id:'cgrow',name:'Close-Grip Bench Press',   cat:'Push',diff:'advanced',    equipment:['barbell','bench'],       muscles:'Triceps, klatka', muscleIds: ['triceps', 'chest']},
  {id:'facepl',name:'Face Pull',               cat:'Pull',diff:'beginner',    equipment:['cable'],                 muscles:'Tylne barki, rotatory', muscleIds: ['back-deltoids', 'upper-back']},
  {id:'calf', name:'Wspięcia na palce',        cat:'Legs',diff:'beginner',    equipment:['bodyweight'],            muscles:'Łydki', muscleIds: ['calves']},
  {id:'lrow', name:'Wiosłowanie w opadzie',    cat:'Pull',diff:'beginner',    equipment:['dumbbells'],             muscles:'Plecy, biceps', muscleIds: ['upper-back', 'lower-back', 'biceps']},
  {id:'incbp',name:'Wyciskanie skośne',        cat:'Push',diff:'intermediate',equipment:['barbell','bench'],       muscles:'Górna klatka, barki', muscleIds: ['chest', 'front-deltoids']},
  {id:'lgcurl',name:'Uginanie nóg leżąc',      cat:'Legs',diff:'intermediate',equipment:['cable'],                 muscles:'Dwugłowe uda', muscleIds: ['hamstring']},
];

export const QUESTIONS = [
  {key:'goal',      text:'👋 Cześć! Jestem **EvoTrain AI** — Twój inteligentny trener personalny.\n\nZanim wygeneruję Twój plan, chcę Cię poznać.\n\nJaki jest Twój **główny cel treningowy**?',  options:['💪 Zwiększenie siły','🏋️ Budowanie masy mięśniowej','🔥 Redukcja tkanki tłuszczowej']},
  {key:'experience',text:'Świetnie! Jakie masz **doświadczenie** treningowe?',                                                                                                                       options:['🌱 Początkujący (< 1 rok)','⚡ Średniozaawansowany (1-3 lata)','🔱 Zaawansowany (3+ lata)']},
  {key:'equipment', text:'Jaki **sprzęt** masz do dyspozycji?',                                                                                                                                     options:['🏪 Pełna siłownia','🏠 Hantle (home gym)','🤸 Tylko masa ciała']},
  {key:'frequency', text:'Ile **dni w tygodniu** możesz trenować?',                                                                                                                                 options:['2 dni','3 dni','4 dni','5+ dni']},
  {key:'injuries',  text:'Ostatnie pytanie! Czy masz jakieś **kontuzje lub ograniczenia**?',                                                                                                        options:['✅ Brak kontuzji','🦵 Problemy z kolanami','🦴 Problemy z kręgosłupem','💪 Problemy z barkami']},
];